config/routes.rb
Rails.application.routes.draw do
  
	root to: "welcome#index", as: "home"
	resources :users

	get '/login', to: "sessions#new"
	post '/login', to: "sessions#create"
	delete '/logout', to: "sessions#destroy"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

	validates :name, presence: true, length: {minimum: 1}

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	before_save {self.email = email.downcase}
	validates :email, uniqueness: {case_sensitive: false}, presence: true,
	                  format: { with: VALID_EMAIL_REGEX }


	has_secure_password
  validates :password, presence: true, length: {minimum: 6}

	# Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

	def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

	def self.digest(string)
	 cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
																								 BCrypt::Engine.cost
	 BCrypt::Password.create(string, cost: cost)
 end

 # Returns a random token.
 def self.new_token
	 SecureRandom.urlsafe_base64
 end

	def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, User.digest(params:[remember_token])
	end


	class << self
	 # Returns the hash digest of the given string.
	 def digest(string)
		 cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
																									 BCrypt::Engine.cost
		 BCrypt::Password.create(string, cost: cost)
	 end

	 # Returns a random token.
	 def new_token
		 SecureRandom.urlsafe_base64
	 end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
			params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
		log_out if logged_in?
    log_out
    redirect_to home_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.create(user_params)
  	if @user.save
  		redirect_to user_path(@user)
  	else
  		render 'new'
  	end
  end

  def show
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	@user.update
  	redirect_to users_path
  end

  def destroy
  	@user = User.find(params[:id])
    @user.destroy
    redirect_to users_path 
  end

private

	def user_params
		params.permit(:name, :email, :password, :password_confirmation)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

	def forget(user)
	user.forget
	cookies.delete(:user_id)
	cookies.delete(:remember_token)
	end
  # Returns the current logged-in user (if any).
  def current_user
		if (user_id = session[:user_id])
		 @current_user ||= User.find_by(id: user_id)
	 elsif (user_id = cookies.signed[:user_id])
		 user = User.find_by(id: user_id)
		 if user && user.authenticated?(cookies[:remember_token])
			 log_in user
			 @current_user = user
		 end
	 end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
		forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
  </small>
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "MEMBERS ONLY", home_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   home_path %></li>
        <li>
            <% if logged_in? %>
            	<%= link_to "Log out", logout_path, method: :delete %>
            <% else %>
	            <%= link_to "Log in", login_path %>
            <% end %>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= yield(:title) %> TOP-SECRET </title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://cdn.rawgit.com/yegor256/tacit/gh-pages/tacit-0.8.1.min.css"/>

    <%= render 'layouts/shim' %>
  </head>

  
  <body>
    <%= render 'layouts/header' %>

    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>NEW USER</h1>

<%= form_tag users_path do %>
<%= render 'shared/error_messages' %>

<%= label_tag 'Name :' %><br>
<%= text_field_tag 'name' %><br>

<%= label_tag 'e-Mail :' %><br>
<%= text_field_tag 'email' %><br>

<%= label_tag 'Password :' %><br>
<%= text_field_tag 'password' %><br>

<%= label_tag 'Password confirmation :' %><br>
<%= text_field_tag 'password_confirmation' %><br>

<%= submit_tag 'Sign-up' %><br>

<% end %>

app/views/users/show.html.erb
<h1><%= 'Welcome ' + @user.name + ' !' %></h1>

app/views/welcome/index.html.erb
<h1>Bienvenue sur ta page d'accueil</h1>



<% if logged_in? %>
	<h2><%=  "session de notre utilisateur" %></h2>
	<% else %>
		<h2><%= link_to 'Sign-up', new_user_path %> Merci de vous inscrire.</h2>
		<% end %>